/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Войти: создаёт сессию и ставит httpOnly-cookie */
        post: operations["Auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Выйти: уничтожает сессию */
        post: operations["Auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Зарегистрироваться: создаёт пользователя, дефолтное расписание и сессию */
        post: operations["Auth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список расписаний текущего пользователя */
        get: operations["Availability_list"];
        put?: never;
        /** @description Создать расписание */
        post: operations["Availability_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/availability/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить расписание */
        get: operations["Availability_get"];
        put?: never;
        post?: never;
        /** @description Удалить расписание */
        delete: operations["Availability_delete"];
        options?: never;
        head?: never;
        /** @description Частично обновить расписание */
        patch: operations["Availability_update"];
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список бронирований текущего пользователя */
        get: operations["Bookings_list"];
        put?: never;
        /** @description Создать бронь (публичный эндпоинт страницы бронирования) */
        post: operations["Bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{bookingUid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить бронь по публичному uid */
        get: operations["Bookings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{bookingUid}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Отменить бронь */
        post: operations["Bookings_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{bookingUid}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Подтвердить бронь (для событий с requiresConfirmation) */
        post: operations["Bookings_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{bookingUid}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Отклонить бронь */
        post: operations["Bookings_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{bookingUid}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Перенести бронь на другое время */
        post: operations["Bookings_reschedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список типов событий текущего пользователя */
        get: operations["EventTypes_list"];
        put?: never;
        /** @description Создать тип события */
        post: operations["EventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{eventTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить тип события по id */
        get: operations["EventTypes_get"];
        put?: never;
        post?: never;
        /** @description Удалить тип события */
        delete: operations["EventTypes_delete"];
        options?: never;
        head?: never;
        /** @description Частично обновить тип события */
        patch: operations["EventTypes_update"];
        trace?: never;
    };
    "/event-types/{eventTypeId}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Скопировать тип события (создаёт копию со слагом `-copy`) */
        post: operations["EventTypes_duplicate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Получить профиль */
        get: operations["Me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Обновить профиль */
        patch: operations["Me_update"];
        trace?: never;
    };
    "/public/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Публичный профиль организатора по username + его открытые события */
        get: operations["Public_organizer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/{username}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Один видимый тип события организатора по слагу (для страницы бронирования) */
        get: operations["Public_eventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Рассчитать доступные времена для бронирования события.
         *     Публичный эндпоинт страницы бронирования.
         */
        get: operations["Slots_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Личная встреча по адресу */
        AddressLocation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "address";
            address: string;
            /**
             * @description Показывать адрес только после подтверждения брони
             * @default true
             */
            displayPublicly: boolean;
        };
        /** @description Личная встреча по адресу */
        AddressLocationMergePatchUpdateReplaceOnly: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "address";
            address: string;
            /**
             * @description Показывать адрес только после подтверждения брони
             * @default true
             */
            displayPublicly: boolean;
        };
        ApiError: {
            /**
             * Format: int32
             * @description HTTP-код ошибки
             */
            code: number;
            /** @description Машиночитаемый код, например `event_type_not_found` */
            errorCode: string;
            /** @description Человекочитаемое описание */
            message: string;
        };
        /** @description Участник встречи */
        Attendee: {
            name: string;
            email: string;
            timeZone: components["schemas"]["TimeZone"];
            /** @description Язык уведомлений участника */
            locale?: string;
            /** @description Телефон — обязателен для событий с локацией `phone` */
            phone?: string;
        };
        /** @description Участник сам выбирает место при бронировании */
        AttendeeDefinedLocation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "attendeeDefined";
        };
        /** @description Участник сам выбирает место при бронировании */
        AttendeeDefinedLocationMergePatchUpdateReplaceOnly: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "attendeeDefined";
        };
        /** @description Интервал доступности в конкретные дни недели */
        AvailabilityRule: {
            /** @description Дни недели, к которым применяется интервал */
            days: components["schemas"]["Weekday"][];
            /**
             * Format: time
             * @description Начало интервала (локальное время расписания), например 09:00
             */
            startTime: string;
            /**
             * Format: time
             * @description Конец интервала, например 18:00
             */
            endTime: string;
        };
        /** @description Интервал доступности в конкретные дни недели */
        AvailabilityRuleMergePatchUpdateReplaceOnly: {
            /** @description Дни недели, к которым применяется интервал */
            days: components["schemas"]["Weekday"][];
            /**
             * Format: time
             * @description Начало интервала (локальное время расписания), например 09:00
             */
            startTime: string;
            /**
             * Format: time
             * @description Конец интервала, например 18:00
             */
            endTime: string;
        };
        /**
         * @example {
         *       "id": 101,
         *       "uid": "bk_a1b2c3d4",
         *       "eventTypeId": 1,
         *       "status": "accepted",
         *       "title": "Интро-звонок: Нина и Алексей Смирнов",
         *       "start": "2026-07-10T10:00:00Z",
         *       "end": "2026-07-10T10:15:00Z",
         *       "organizer": {
         *         "id": 1,
         *         "username": "nina",
         *         "name": "Нина Хабарова",
         *         "email": "khabarova.ninaa@gmail.com",
         *         "timeZone": "Europe/Moscow",
         *         "createdAt": "2026-01-15T09:00:00Z"
         *       },
         *       "attendees": [
         *         {
         *           "name": "Алексей Смирнов",
         *           "email": "aleksey@example.com",
         *           "timeZone": "Europe/Moscow"
         *         }
         *       ],
         *       "location": {
         *         "type": "integration",
         *         "integration": "google-meet"
         *       },
         *       "meetingUrl": "https://meet.google.com/abc-defg-hij",
         *       "createdAt": "2026-07-01T12:00:00Z",
         *       "updatedAt": "2026-07-01T12:00:00Z"
         *     }
         */
        Booking: {
            /** Format: int64 */
            readonly id: number;
            /** @description Публичный идентификатор брони, используется в ссылках управления */
            readonly uid: string;
            /** Format: int64 */
            readonly eventTypeId: number;
            readonly status: components["schemas"]["BookingStatus"];
            /** @description Заголовок встречи в календаре */
            readonly title: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            readonly end: string;
            readonly organizer: components["schemas"]["User"];
            attendees: components["schemas"]["Attendee"][];
            /** @description Email-адреса дополнительных гостей */
            guests?: string[];
            /** @description Выбранное место проведения */
            location: Omit<components["schemas"]["EventLocation"], "type">;
            /**
             * Format: uri
             * @description Ссылка на видеовстречу, если место — интеграция
             */
            readonly meetingUrl?: string;
            /** @description Ответы на кастомные поля формы: ключ — `name` поля */
            bookingFieldsResponses?: Record<string, never>;
            /** @description Причина отмены */
            readonly cancellationReason?: string;
            /** @description Причина отклонения организатором */
            readonly rejectionReason?: string;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
        };
        /** @description Дополнительное поле формы бронирования */
        BookingField: {
            type: components["schemas"]["BookingFieldType"];
            /** @description Ключ поля в ответах участника */
            name: components["schemas"]["Slug"];
            /** @description Подпись поля в форме */
            label: string;
            /** @default false */
            required: boolean;
            placeholder?: string;
            /** @description Варианты для select / multiselect / radio */
            options?: string[];
            /**
             * @description Скрытое поле, заполняется через query-параметры ссылки
             * @default false
             */
            hidden: boolean;
        };
        /** @description Дополнительное поле формы бронирования */
        BookingFieldMergePatchUpdateReplaceOnly: {
            type: components["schemas"]["BookingFieldType"];
            /** @description Ключ поля в ответах участника */
            name: components["schemas"]["Slug"];
            /** @description Подпись поля в форме */
            label: string;
            /** @default false */
            required: boolean;
            placeholder?: string;
            /** @description Варианты для select / multiselect / radio */
            options?: string[];
            /**
             * @description Скрытое поле, заполняется через query-параметры ссылки
             * @default false
             */
            hidden: boolean;
        };
        /** @enum {string} */
        BookingFieldType: "text" | "textarea" | "number" | "email" | "phone" | "select" | "multiselect" | "checkbox" | "radio" | "boolean";
        /** @description Ограничение плотности бронирований */
        BookingLimits: {
            /**
             * Format: int32
             * @description Максимум броней в день
             */
            day?: number;
            /**
             * Format: int32
             * @description Максимум броней в неделю
             */
            week?: number;
            /**
             * Format: int32
             * @description Максимум броней в месяц
             */
            month?: number;
            /**
             * Format: int32
             * @description Максимум броней в год
             */
            year?: number;
        };
        /** @description Ограничение плотности бронирований */
        BookingLimitsMergePatchUpdateOrCreate: {
            /** @description Максимум броней в день */
            day?: number | null;
            /** @description Максимум броней в неделю */
            week?: number | null;
            /** @description Максимум броней в месяц */
            month?: number | null;
            /** @description Максимум броней в год */
            year?: number | null;
        };
        /** @enum {string} */
        BookingStatus: "pending" | "accepted" | "rejected" | "cancelled";
        CancelBookingRequest: {
            reason?: string;
        };
        /** @description Запрос на создание брони (публичный, без авторизации) */
        CreateBookingRequest: {
            /** Format: int64 */
            eventTypeId: number;
            /**
             * Format: date-time
             * @description Начало слота
             */
            start: string;
            /**
             * Format: int32
             * @description Выбранная длительность, если событие поддерживает варианты
             */
            lengthInMinutes?: number;
            attendee: components["schemas"]["Attendee"];
            guests?: string[];
            /** @description Выбранное место из `locations` события */
            location?: Omit<components["schemas"]["EventLocation"], "type">;
            /** @description Ответы на кастомные поля формы */
            bookingFieldsResponses?: Record<string, never>;
            /** @description Метаданные интеграции, до 50 пар ключ-значение */
            metadata?: Record<string, never>;
        };
        /** @description Переопределение доступности на конкретную дату */
        DateOverride: {
            /** Format: date */
            date: string;
            /** @description Интервалы доступности в эту дату; пустой массив — день недоступен */
            intervals: {
                /** Format: time */
                startTime: string;
                /** Format: time */
                endTime: string;
            }[];
        };
        /** @description Переопределение доступности на конкретную дату */
        DateOverrideMergePatchUpdateReplaceOnly: {
            /** Format: date */
            date: string;
            /** @description Интервалы доступности в эту дату; пустой массив — день недоступен */
            intervals: {
                /** Format: time */
                startTime: string;
                /** Format: time */
                endTime: string;
            }[];
        };
        /** @description Способ проведения встречи */
        EventLocation: components["schemas"]["AddressLocation"] | components["schemas"]["LinkLocation"] | components["schemas"]["PhoneLocation"] | components["schemas"]["IntegrationLocation"] | components["schemas"]["AttendeeDefinedLocation"];
        /** @description Способ проведения встречи */
        EventLocationMergePatchUpdateReplaceOnly: components["schemas"]["AddressLocationMergePatchUpdateReplaceOnly"] | components["schemas"]["LinkLocationMergePatchUpdateReplaceOnly"] | components["schemas"]["PhoneLocationMergePatchUpdateReplaceOnly"] | components["schemas"]["IntegrationLocationMergePatchUpdateReplaceOnly"] | components["schemas"]["AttendeeDefinedLocationMergePatchUpdateReplaceOnly"];
        /** @description Оплата за бронирование */
        EventPrice: {
            /**
             * Format: int64
             * @description Сумма в минимальных единицах валюты (копейки, центы)
             */
            amount: number;
            /** @description Код валюты ISO 4217, например `RUB`, `USD` */
            currency: string;
        };
        /** @description Оплата за бронирование */
        EventPriceMergePatchUpdateOrCreate: {
            /**
             * Format: int64
             * @description Сумма в минимальных единицах валюты (копейки, центы)
             */
            amount?: number;
            /** @description Код валюты ISO 4217, например `RUB`, `USD` */
            currency?: string;
        };
        /**
         * @description Тип события — то, что участники могут забронировать
         * @example {
         *       "id": 1,
         *       "title": "Интро-звонок",
         *       "slug": "intro",
         *       "description": "Короткое знакомство на 15 минут.",
         *       "lengthInMinutes": 15,
         *       "locations": [
         *         {
         *           "type": "integration",
         *           "integration": "google-meet"
         *         }
         *       ],
         *       "hidden": false,
         *       "requiresConfirmation": false,
         *       "disableGuests": false,
         *       "minimumBookingNotice": 120,
         *       "beforeEventBuffer": 0,
         *       "afterEventBuffer": 0,
         *       "bookingWindowDays": 60,
         *       "schedulingType": "individual",
         *       "scheduleId": 1,
         *       "ownerId": 1,
         *       "createdAt": "2026-01-15T09:00:00Z",
         *       "updatedAt": "2026-01-15T09:00:00Z"
         *     }
         */
        EventType: {
            /** Format: int64 */
            readonly id: number;
            /** @description Название, например «Интро-звонок 30 минут» */
            title: string;
            /** @description Слаг в ссылке бронирования: /{username}/{slug} */
            slug: components["schemas"]["Slug"];
            /** @description Описание, показывается на странице бронирования (поддерживает Markdown) */
            description?: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах
             */
            lengthInMinutes: number;
            /** @description Альтернативные длительности, из которых выбирает участник */
            lengthInMinutesOptions?: number[];
            /** @description Где проходит встреча; участник выбирает один из вариантов */
            locations: components["schemas"]["EventLocation"][];
            /** @description Дополнительные поля формы бронирования */
            bookingFields?: components["schemas"]["BookingField"][];
            /**
             * @description Скрыть событие с публичной страницы профиля
             * @default false
             */
            hidden: boolean;
            /**
             * @description Требуется ручное подтверждение брони организатором
             * @default false
             */
            requiresConfirmation: boolean;
            /**
             * @description Запретить участнику добавлять гостей
             * @default false
             */
            disableGuests: boolean;
            /**
             * Format: int32
             * @description Минимальный интервал до начала встречи, за который можно бронировать (в минутах)
             * @default 120
             */
            minimumBookingNotice: number;
            /**
             * Format: int32
             * @description Буфер до встречи в минутах
             * @default 0
             */
            beforeEventBuffer: number;
            /**
             * Format: int32
             * @description Буфер после встречи в минутах
             * @default 0
             */
            afterEventBuffer: number;
            /**
             * Format: int32
             * @description Шаг сетки слотов в минутах; по умолчанию равен длительности
             */
            slotInterval?: number;
            /**
             * Format: int32
             * @description Количество мест в одном слоте (групповые события)
             */
            seatsPerTimeSlot?: number;
            /**
             * Format: int32
             * @description На сколько дней вперёд открыто бронирование
             * @default 60
             */
            bookingWindowDays: number;
            /** @description Лимиты на количество броней */
            bookingLimits?: components["schemas"]["BookingLimits"];
            /** @description Настройки повторяющегося события */
            recurrence?: components["schemas"]["Recurrence"];
            /**
             * @description Тип распределения для командных событий
             * @default individual
             */
            schedulingType: components["schemas"]["SchedulingType"];
            /** @description Платное событие */
            price?: components["schemas"]["EventPrice"];
            /**
             * Format: int64
             * @description Расписание доступности; если не задано — расписание владельца по умолчанию
             */
            scheduleId?: number;
            /**
             * Format: int64
             * @description Владелец события
             */
            readonly ownerId: number;
            /** Format: date-time */
            readonly createdAt: string;
            /** Format: date-time */
            readonly updatedAt: string;
        };
        /**
         * @description Тип события — то, что участники могут забронировать
         * @example {
         *       "title": "Интро-звонок",
         *       "slug": "intro",
         *       "description": "Короткое знакомство на 15 минут.",
         *       "lengthInMinutes": 15,
         *       "locations": [
         *         {
         *           "type": "integration",
         *           "integration": "google-meet"
         *         }
         *       ],
         *       "hidden": false,
         *       "requiresConfirmation": false,
         *       "disableGuests": false,
         *       "minimumBookingNotice": 120,
         *       "beforeEventBuffer": 0,
         *       "afterEventBuffer": 0,
         *       "bookingWindowDays": 60,
         *       "schedulingType": "individual",
         *       "scheduleId": 1
         *     }
         */
        EventTypeMergePatchUpdate: {
            /** @description Название, например «Интро-звонок 30 минут» */
            title?: string;
            /** @description Слаг в ссылке бронирования: /{username}/{slug} */
            slug?: components["schemas"]["Slug"];
            /** @description Описание, показывается на странице бронирования (поддерживает Markdown) */
            description?: string | null;
            /**
             * Format: int32
             * @description Длительность встречи в минутах
             */
            lengthInMinutes?: number;
            /** @description Альтернативные длительности, из которых выбирает участник */
            lengthInMinutesOptions?: number[] | null;
            /** @description Где проходит встреча; участник выбирает один из вариантов */
            locations?: components["schemas"]["EventLocationMergePatchUpdateReplaceOnly"][];
            /** @description Дополнительные поля формы бронирования */
            bookingFields?: components["schemas"]["BookingFieldMergePatchUpdateReplaceOnly"][] | null;
            /** @description Скрыть событие с публичной страницы профиля */
            hidden?: boolean | null;
            /** @description Требуется ручное подтверждение брони организатором */
            requiresConfirmation?: boolean | null;
            /** @description Запретить участнику добавлять гостей */
            disableGuests?: boolean | null;
            /** @description Минимальный интервал до начала встречи, за который можно бронировать (в минутах) */
            minimumBookingNotice?: number | null;
            /** @description Буфер до встречи в минутах */
            beforeEventBuffer?: number | null;
            /** @description Буфер после встречи в минутах */
            afterEventBuffer?: number | null;
            /** @description Шаг сетки слотов в минутах; по умолчанию равен длительности */
            slotInterval?: number | null;
            /** @description Количество мест в одном слоте (групповые события) */
            seatsPerTimeSlot?: number | null;
            /** @description На сколько дней вперёд открыто бронирование */
            bookingWindowDays?: number | null;
            /** @description Лимиты на количество броней */
            bookingLimits?: components["schemas"]["BookingLimitsMergePatchUpdateOrCreate"] | null;
            /** @description Настройки повторяющегося события */
            recurrence?: components["schemas"]["RecurrenceMergePatchUpdateOrCreate"] | null;
            /** @description Тип распределения для командных событий */
            schedulingType?: components["schemas"]["SchedulingType"] | null;
            /** @description Платное событие */
            price?: components["schemas"]["EventPriceMergePatchUpdateOrCreate"] | null;
            /** @description Расписание доступности; если не задано — расписание владельца по умолчанию */
            scheduleId?: number | null;
        };
        /** @description Видеовстреча через интеграцию */
        IntegrationLocation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "integration";
            /** @enum {string} */
            integration: "google-meet" | "zoom" | "ms-teams" | "daily";
        };
        /** @description Видеовстреча через интеграцию */
        IntegrationLocationMergePatchUpdateReplaceOnly: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "integration";
            /** @enum {string} */
            integration: "google-meet" | "zoom" | "ms-teams" | "daily";
        };
        /** @description Встреча по произвольной ссылке */
        LinkLocation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "link";
            /** Format: uri */
            link: string;
        };
        /** @description Встреча по произвольной ссылке */
        LinkLocationMergePatchUpdateReplaceOnly: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "link";
            /** Format: uri */
            link: string;
        };
        /** @description Вход по email и паролю */
        LoginRequest: {
            email: string;
            password: string;
        };
        /** @description Телефонный звонок: организатор звонит участнику */
        PhoneLocation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "phone";
            /** @description Номер организатора; если не задан — берётся номер участника */
            phone?: string;
        };
        /** @description Телефонный звонок: организатор звонит участнику */
        PhoneLocationMergePatchUpdateReplaceOnly: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "phone";
            /** @description Номер организатора; если не задан — берётся номер участника */
            phone?: string;
        };
        /**
         * @description Публичный профиль организатора и его открытые события
         * @example {
         *       "id": 1,
         *       "username": "nina",
         *       "name": "Нина Хабарова",
         *       "timeZone": "Europe/Moscow",
         *       "eventTypes": []
         *     }
         */
        PublicOrganizer: {
            /** Format: int64 */
            id: number;
            /** @description Публичный username из ссылки бронирования */
            username: components["schemas"]["Slug"];
            name: string;
            timeZone: components["schemas"]["TimeZone"];
            /** Format: uri */
            avatarUrl?: string;
            /** @description Видимые (не скрытые) типы событий организатора */
            eventTypes: components["schemas"]["EventType"][];
        };
        /** @description Периодичность повторяющегося события */
        Recurrence: {
            /** @enum {string} */
            frequency: "daily" | "weekly" | "monthly";
            /**
             * Format: int32
             * @description Интервал повторения: каждые N периодов
             * @default 1
             */
            interval: number;
            /**
             * Format: int32
             * @description Максимальное число повторений
             */
            count: number;
        };
        /** @description Периодичность повторяющегося события */
        RecurrenceMergePatchUpdateOrCreate: {
            /** @enum {string} */
            frequency?: "daily" | "weekly" | "monthly";
            /** @description Интервал повторения: каждые N периодов */
            interval?: number | null;
            /**
             * Format: int32
             * @description Максимальное число повторений
             */
            count?: number;
        };
        /** @description Регистрация нового организатора */
        RegisterRequest: {
            name: string;
            email: string;
            password: string;
            timeZone: components["schemas"]["TimeZone"];
            /** @description Публичный username из ссылки бронирования */
            username: components["schemas"]["Slug"];
            /** @description Локаль интерфейса, например `ru` */
            locale?: string;
        };
        RejectBookingRequest: {
            reason?: string;
        };
        RescheduleBookingRequest: {
            /**
             * Format: date-time
             * @description Новое начало встречи
             */
            start: string;
            reason?: string;
        };
        /**
         * @description Расписание доступности организатора
         * @example {
         *       "id": 1,
         *       "name": "Рабочие часы",
         *       "timeZone": "Europe/Moscow",
         *       "availability": [
         *         {
         *           "days": [
         *             "monday",
         *             "tuesday",
         *             "wednesday",
         *             "thursday",
         *             "friday"
         *           ],
         *           "startTime": "09:00:00",
         *           "endTime": "18:00:00"
         *         }
         *       ],
         *       "isDefault": true,
         *       "ownerId": 1
         *     }
         */
        Schedule: {
            /** Format: int64 */
            readonly id: number;
            /** @description Название, например «Рабочие часы» */
            name: string;
            timeZone: components["schemas"]["TimeZone"];
            /** @description Правила еженедельной доступности */
            availability: components["schemas"]["AvailabilityRule"][];
            /** @description Переопределения на конкретные даты */
            overrides?: components["schemas"]["DateOverride"][];
            /**
             * @description Использовать как расписание по умолчанию
             * @default false
             */
            isDefault: boolean;
            /** Format: int64 */
            readonly ownerId: number;
        };
        /**
         * @description Расписание доступности организатора
         * @example {
         *       "name": "Рабочие часы",
         *       "timeZone": "Europe/Moscow",
         *       "availability": [
         *         {
         *           "days": [
         *             "monday",
         *             "tuesday",
         *             "wednesday",
         *             "thursday",
         *             "friday"
         *           ],
         *           "startTime": "09:00:00",
         *           "endTime": "18:00:00"
         *         }
         *       ],
         *       "isDefault": true
         *     }
         */
        ScheduleMergePatchUpdate: {
            /** @description Название, например «Рабочие часы» */
            name?: string;
            timeZone?: components["schemas"]["TimeZone"];
            /** @description Правила еженедельной доступности */
            availability?: components["schemas"]["AvailabilityRuleMergePatchUpdateReplaceOnly"][];
            /** @description Переопределения на конкретные даты */
            overrides?: components["schemas"]["DateOverrideMergePatchUpdateReplaceOnly"][] | null;
            /** @description Использовать как расписание по умолчанию */
            isDefault?: boolean | null;
        };
        /**
         * @description Как распределяются брони между участниками команды
         * @enum {string}
         */
        SchedulingType: "individual" | "collective" | "roundRobin";
        /** @description Свободный слот для бронирования */
        Slot: {
            /**
             * Format: date-time
             * @description Начало доступного слота
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец слота
             */
            end: string;
            /**
             * Format: int32
             * @description Осталось мест — только для групповых событий с `seatsPerTimeSlot`
             */
            seatsRemaining?: number;
        };
        /**
         * @description Доступные слоты в запрошенном диапазоне, отсортированы по времени начала
         * @example {
         *       "timeZone": "Europe/Moscow",
         *       "slots": [
         *         {
         *           "start": "2026-07-10T09:00:00Z",
         *           "end": "2026-07-10T09:15:00Z"
         *         },
         *         {
         *           "start": "2026-07-10T09:15:00Z",
         *           "end": "2026-07-10T09:30:00Z"
         *         },
         *         {
         *           "start": "2026-07-11T12:00:00Z",
         *           "end": "2026-07-11T12:15:00Z",
         *           "seatsRemaining": 3
         *         }
         *       ]
         *     }
         */
        SlotsResponse: {
            /** @description Свободные слоты; время в UTC, группировать по дате можно на клиенте */
            slots: components["schemas"]["Slot"][];
            /** @description Таймзона, в которой рассчитаны слоты (совпадает с запрошенной) */
            timeZone: components["schemas"]["TimeZone"];
        };
        /** @description URL-слаг: строчные буквы, цифры и дефисы */
        Slug: string;
        /** @description IANA-таймзона, например `Europe/Moscow` */
        TimeZone: string;
        /**
         * @example {
         *       "id": 1,
         *       "username": "nina",
         *       "name": "Нина Хабарова",
         *       "email": "khabarova.ninaa@gmail.com",
         *       "timeZone": "Europe/Moscow",
         *       "locale": "ru",
         *       "defaultScheduleId": 1,
         *       "createdAt": "2026-01-15T09:00:00Z"
         *     }
         */
        User: {
            /** Format: int64 */
            readonly id: number;
            /** @description Публичный username, входит в ссылку бронирования: /{username}/{eventSlug} */
            username: components["schemas"]["Slug"];
            name: string;
            email: string;
            timeZone: components["schemas"]["TimeZone"];
            /** @description Локаль интерфейса, например `ru` или `en` */
            locale?: string;
            /** Format: uri */
            avatarUrl?: string;
            /**
             * Format: int64
             * @description Расписание доступности по умолчанию
             */
            defaultScheduleId?: number;
            /** Format: date-time */
            readonly createdAt: string;
        };
        /**
         * @example {
         *       "username": "nina",
         *       "name": "Нина Хабарова",
         *       "email": "khabarova.ninaa@gmail.com",
         *       "timeZone": "Europe/Moscow",
         *       "locale": "ru",
         *       "defaultScheduleId": 1
         *     }
         */
        UserMergePatchUpdate: {
            /** @description Публичный username, входит в ссылку бронирования: /{username}/{eventSlug} */
            username?: components["schemas"]["Slug"];
            name?: string;
            email?: string;
            timeZone?: components["schemas"]["TimeZone"];
            /** @description Локаль интерфейса, например `ru` или `en` */
            locale?: string | null;
            avatarUrl?: string | null;
            /** @description Расписание доступности по умолчанию */
            defaultScheduleId?: number | null;
        };
        /** @enum {string} */
        Weekday: "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
    };
    responses: never;
    parameters: {
        "PaginationParams.skip": number;
        "PaginationParams.take": number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Auth_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Availability_list: {
        parameters: {
            query?: {
                skip?: components["parameters"]["PaginationParams.skip"];
                take?: components["parameters"]["PaginationParams.take"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Schedule"][];
                        /**
                         * Format: int32
                         * @description Общее количество записей
                         * @example 1
                         */
                        totalCount: number;
                    };
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Availability_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Schedule"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Availability_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Availability_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Availability_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["ScheduleMergePatchUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Bookings_list: {
        parameters: {
            query?: {
                skip?: components["parameters"]["PaginationParams.skip"];
                take?: components["parameters"]["PaginationParams.take"];
                status?: components["schemas"]["BookingStatus"];
                eventTypeId?: number;
                /** @description Брони, начинающиеся не раньше этой даты */
                afterStart?: string;
                /** @description Брони, начинающиеся не позже этой даты */
                beforeEnd?: string;
                /** @description Поиск по имени или email участника */
                attendeeEmail?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Booking"][];
                        /**
                         * Format: int32
                         * @description Общее количество записей
                         * @example 1
                         */
                        totalCount: number;
                    };
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Bookings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingUid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Bookings_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingUid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Bookings_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingUid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Bookings_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingUid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Bookings_reschedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingUid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RescheduleBookingRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: {
                skip?: components["parameters"]["PaginationParams.skip"];
                take?: components["parameters"]["PaginationParams.take"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["EventType"][];
                        /**
                         * Format: int32
                         * @description Общее количество записей
                         * @example 1
                         */
                        totalCount: number;
                    };
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventType"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["EventTypeMergePatchUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_duplicate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["UserMergePatchUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Public_organizer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicOrganizer"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Public_eventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                slug: components["schemas"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Slots_list: {
        parameters: {
            query: {
                /** @description Тип события, для которого считаются слоты */
                eventTypeId: number;
                /** @description Начало диапазона (дата включительно) */
                start: string;
                /** @description Конец диапазона (дата включительно) */
                end: string;
                /** @description Таймзона участника; по умолчанию — таймзона расписания */
                timeZone?: components["schemas"]["TimeZone"];
                /** @description Выбранная длительность в минутах для событий с `lengthInMinutesOptions` */
                duration?: number;
                /**
                 * @description Переопределить расписание доступности (для предпросмотра при
                 *     редактировании типа события); по умолчанию — расписание события
                 */
                scheduleId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsResponse"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
